# Generated by Django 4.1 on 2023-01-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='places_available',
            field=models.IntegerField(default=0),
        ),
    ]
